### ISSUE TITLE
Mask Detection is not working on Front Camera.

### ISSUE THREAD

**Issue by rushidalvi** [estebanuri/facemaskdetector#4]
This is great app ,but only issue is its not detecting mask on front camera.if i rotate  phone  180 degree then its detecting but its wrong ,can you  pls solve this...

**Comment by rushidalvi** [comment]
I found Solution..
In DetectorActivity.java. Add Following Code..and it will work in portrait mode with front camera
#
Private  Bitmap newrgbFrameBitmap=null;
 rgbFrameBitmap.setPixels(getRgbBytes(), 0, previewWidth, 0, 0, previewWidth, previewHeight);
    //##########################################here_change####################################################
    if (getCameraFacing() == CameraCharacteristics.LENS_FACING_FRONT) {
      Matrix rgbmatrix = new Matrix();
      rgbmatrix.postRotate(180);
      newrgbFrameBitmap = Bitmap.createBitmap(rgbFrameBitmap, 0, 0, rgbFrameBitmap.getWidth(), rgbFrameBitmap.getHeight(), rgbmatrix, true);
      rgbFrameBitmap = newrgbFrameBitmap;
    }
readyForNextImage();

Thanks...

**Comment by estebanuri** [comment]
> I found Solution..
> In DetectorActivity.java. Add Following Code..and it will work in portrait mode with front camera
> 
> Private Bitmap newrgbFrameBitmap=null;
> rgbFrameBitmap.setPixels(getRgbBytes(), 0, previewWidth, 0, 0, previewWidth, previewHeight);
> //##########################################here_change####################################################
> if (getCameraFacing() == CameraCharacteristics.LENS_FACING_FRONT) {
> Matrix rgbmatrix = new Matrix();
> rgbmatrix.postRotate(180);
> newrgbFrameBitmap = Bitmap.createBitmap(rgbFrameBitmap, 0, 0, rgbFrameBitmap.getWidth(), rgbFrameBitmap.getHeight(), rgbmatrix, true);
> rgbFrameBitmap = newrgbFrameBitmap;
> }
> readyForNextImage();
> 
> Thanks...

I (think) I've patched the frontal camera issue.
I didn't use this solution because it didn't work on my phone

**Comment by Ron81** [comment]
> I (think) I've patched the frontal camera issue.
> I didn't use this solution because it didn't work on my phone

I have a Tablet on Oreo 8.1, with frontal camera, but no back camera, and the App refuses to start. 
I tried to apply the code above, but w/o luck. Please advise on what i could try to get it to run.
__________________________________________________________________
I/CameraManagerGlobal: Connecting to camera service
D/tensorflow: CameraActivity: onStart org.tensorflow.lite.examples.detection.DetectorActivity@86d5c16
D/tensorflow: CameraActivity: onResume org.tensorflow.lite.examples.detection.DetectorActivity@86d5c16
D/OpenGLRenderer: HWUI GL Pipeline
D/: HostConnection::get() New Host Connection established 0xdfb1e680, tid 6181
I/zygote: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
I/OpenGLRenderer: Initialized EGL, version 1.4
D/OpenGLRenderer: Swap behavior 1
W/OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
D/OpenGLRenderer: Swap behavior 0
D/EGL_emulation: eglCreateContext: 0xe95e5100: maj 3 min 1 rcv 4
D/EGL_emulation: eglMakeCurrent: 0xe95e5100: ver 3 1 (tinfo 0xe951b6e0)
E/eglCodecCommon: glUtilsParamSize: unknow param 0x000082da
E/eglCodecCommon: glUtilsParamSize: unknow param 0x000082da
**W/CameraBase: An error occurred while connecting to camera -1: Status(-8): '4: validateConnectLocked:866: No camera device with ID "-1" available'**
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.tensorflow.lite.examples.facemask, PID: 6131
    java.lang.RuntimeException: Fail to connect to camera service
        at android.hardware.Camera.<init>(Camera.java:519)
        at android.hardware.Camera.open(Camera.java:365)
        at org.tensorflow.lite.examples.detection.LegacyCameraConnectionFragment$1.onSurfaceTextureAvailable(LegacyCameraConnectionFragment.java:71)
        at android.view.TextureView.getHardwareLayer(TextureView.java:390)
        at android.view.TextureView.draw(TextureView.java:339)
        at android.view.View.updateDisplayListIfDirty(View.java:18142)
        at android.view.View.draw(View.java:18920)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
        at android.view.View.updateDisplayListIfDirty(View.java:18133)
        at android.view.View.draw(View.java:18920)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
        at android.view.View.updateDisplayListIfDirty(View.java:18133)
        at android.view.View.draw(View.java:18920)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
        at android.view.View.draw(View.java:19195)
        at android.view.View.updateDisplayListIfDirty(View.java:18142)
        at android.view.View.draw(View.java:18920)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1246)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
        at android.view.View.draw(View.java:19195)
        at android.view.View.updateDisplayListIfDirty(View.java:18142)
        at android.view.View.draw(View.java:18920)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
        at android.view.View.updateDisplayListIfDirty(View.java:18133)
        at android.view.View.draw(View.java:18920)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
        at android.view.View.updateDisplayListIfDirty(View.java:18133)
        at android.view.View.draw(View.java:18920)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
        at android.view.View.updateDisplayListIfDirty(View.java:18133)
        at android.view.View.draw(View.java:18920)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
        at android.view.View.updateDisplayListIfDirty(View.java:18133)
        at android.view.View.draw(View.java:18920)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
        at android.view.View.draw(View.java:19195)
        at com.android.internal.policy.DecorView.draw(DecorView.java:788)
        at android.view.View.updateDisplayListIfDirty(View.java:18142)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:669)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:675)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:783)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:2992)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2806)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2359)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1392)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6752)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
        at android.view.Choreographer.doCallbacks(Choreographer.java:723)
        at android.view.Choreographer.doFrame(Choreographer.java:658)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by mjuda** [comment]
To everyone who still have issue using APK stored on github: apk is not updated and contains this issue but project from master branch has it fixed
